name: admin_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.8.0
  dart_mappable: ^4.5.0
  get_it: ^8.0.3
  retrofit: ^4.4.2
  dartz: ^0.10.1
  logger: ^2.5.0
  path_provider: ^2.1.5
  flutter_bloc: ^9.1.1
  responsive_framework: ^1.5.1
  window_manager: ^0.4.3
  dio: ^5.8.0+1
  equatable: ^2.0.7
  connectivity_plus: ^6.1.4
  get: ^4.7.2
  fluent_ui: ^4.12.0
  clipboard: ^2.0.2
  shared_preferences: ^2.5.3
  loader_overlay: ^5.0.0
  flutter_spinkit: ^5.2.1
  system_theme: ^3.1.2
  intl: ^0.20.2
  flutter_svg: ^2.2.0
  path: ^1.9.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  http: ^1.5.0-beta.2
  geocoding: ^4.0.0
  syncfusion_flutter_datepicker: ^30.2.6
  syncfusion_flutter_datagrid: ^30.2.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  dart_mappable_builder: ^4.3.1+1
  retrofit_generator: ^8.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/bf_logo.jpg
    - assets/images/
    - assets/icons/
    - assets/lang/
    - assets/lang/en_US.json
    - assets/lang/pt_BR.json
    - assets/fonts/OpenSans-Regular.ttf
    - assets/fonts/OpenSans-Bold.ttf
    - assets/fonts/OpenSans-Italic.ttf
    - assets/fonts/OpenSans-BoldItalic.ttf
