"""empty message

Revision ID: 665437ed1d06
Revises: 6dddb353f3b1
Create Date: 2025-08-21 10:40:59.580747

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '665437ed1d06'
down_revision = '6dddb353f3b1'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TblJobOrder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bpId', sa.Integer(), nullable=False),
    sa.Column('jobDate', sa.DateTime(), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jobDescription', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pickupAddress', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deliveryAddress', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pickupLat', sa.Float(), nullable=False),
    sa.Column('pickupLong', sa.Float(), nullable=False),
    sa.Column('deliveryLat', sa.Float(), nullable=False),
    sa.Column('deliveryLong', sa.Float(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['bpId'], ['TblBusinessPartner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TblJobOrder_bpId'), 'TblJobOrder', ['bpId'], unique=False)
    op.create_index(op.f('ix_TblJobOrder_id'), 'TblJobOrder', ['id'], unique=False)
    op.create_index(op.f('ix_TblJobOrder_reference'), 'TblJobOrder', ['reference'], unique=True)
    op.create_index(op.f('ix_TblJobOrder_status'), 'TblJobOrder', ['status'], unique=False)
    op.create_table('TblJobOrderLog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('jobOrderId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['TblUser.id'], ),
    sa.ForeignKeyConstraint(['jobOrderId'], ['TblJobOrder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TblJobOrderLog_created_by'), 'TblJobOrderLog', ['created_by'], unique=False)
    op.create_index(op.f('ix_TblJobOrderLog_id'), 'TblJobOrderLog', ['id'], unique=False)
    op.create_index(op.f('ix_TblJobOrderLog_jobOrderId'), 'TblJobOrderLog', ['jobOrderId'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TblJobOrderLog_jobOrderId'), table_name='TblJobOrderLog')
    op.drop_index(op.f('ix_TblJobOrderLog_id'), table_name='TblJobOrderLog')
    op.drop_index(op.f('ix_TblJobOrderLog_created_by'), table_name='TblJobOrderLog')
    op.drop_table('TblJobOrderLog')
    op.drop_index(op.f('ix_TblJobOrder_status'), table_name='TblJobOrder')
    op.drop_index(op.f('ix_TblJobOrder_reference'), table_name='TblJobOrder')
    op.drop_index(op.f('ix_TblJobOrder_id'), table_name='TblJobOrder')
    op.drop_index(op.f('ix_TblJobOrder_bpId'), table_name='TblJobOrder')
    op.drop_table('TblJobOrder')
    # ### end Alembic commands ###
