"""empty message

Revision ID: 6dddb353f3b1
Revises: 
Create Date: 2025-08-09 09:33:43.162500

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '6dddb353f3b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TblBusinessPartner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('bpName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bpType', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contactPerson', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contactNumber', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['TblUser.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['TblUser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TblBusinessPartner_bpName'), 'TblBusinessPartner', ['bpName'], unique=True)
    op.create_index(op.f('ix_TblBusinessPartner_created_by'), 'TblBusinessPartner', ['created_by'], unique=False)
    op.create_index(op.f('ix_TblBusinessPartner_id'), 'TblBusinessPartner', ['id'], unique=False)
    op.create_table('TblBpLogNote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('bpId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bpId'], ['TblBusinessPartner.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['TblUser.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['TblUser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TblBpLogNote_bpId'), 'TblBpLogNote', ['bpId'], unique=False)
    op.create_index(op.f('ix_TblBpLogNote_created_by'), 'TblBpLogNote', ['created_by'], unique=False)
    op.create_index(op.f('ix_TblBpLogNote_id'), 'TblBpLogNote', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TblBpLogNote_id'), table_name='TblBpLogNote')
    op.drop_index(op.f('ix_TblBpLogNote_created_by'), table_name='TblBpLogNote')
    op.drop_index(op.f('ix_TblBpLogNote_bpId'), table_name='TblBpLogNote')
    op.drop_table('TblBpLogNote')
    op.drop_index(op.f('ix_TblBusinessPartner_id'), table_name='TblBusinessPartner')
    op.drop_index(op.f('ix_TblBusinessPartner_created_by'), table_name='TblBusinessPartner')
    op.drop_index(op.f('ix_TblBusinessPartner_bpName'), table_name='TblBusinessPartner')
    op.drop_table('TblBusinessPartner')
    # ### end Alembic commands ###
