"""empty message

Revision ID: 33b11f61e919
Revises: a19c5ebad3f4
Create Date: 2025-08-25 09:00:13.139367

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '33b11f61e919'
down_revision = 'a19c5ebad3f4'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TblJobOrder', sa.Column('contactNumber', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TblJobOrder', 'contactNumber')
    # ### end Alembic commands ###
