"""empty message

Revision ID: 0e7be7c2d88f
Revises: 6b34030e1255
Create Date: 2025-09-19 09:47:14.375303

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '0e7be7c2d88f'
down_revision = '6b34030e1255'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TblEmployee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employeeId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('firstName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lastName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phoneNumber', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dateStarted', sa.DateTime(), nullable=False),
    sa.Column('positionCode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dailyRate', sa.Float(), nullable=False),
    sa.Column('sss_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('philhealth_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pagibig_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tax_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sssContri', sa.Float(), nullable=True),
    sa.Column('philhealthContri', sa.Float(), nullable=True),
    sa.Column('pagibigContri', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('sickLeave', sa.Integer(), nullable=True),
    sa.Column('vacationLeave', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['positionCode'], ['TblEmplPosition.code'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TblEmployee_employeeId'), 'TblEmployee', ['employeeId'], unique=True)
    op.create_index(op.f('ix_TblEmployee_id'), 'TblEmployee', ['id'], unique=False)
    op.create_table('TblLogEmployee',
    sa.Column('logNotes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['TblUser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TblLogEmployee_created_by'), 'TblLogEmployee', ['created_by'], unique=False)
    op.create_index(op.f('ix_TblLogEmployee_id'), 'TblLogEmployee', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TblLogEmployee_id'), table_name='TblLogEmployee')
    op.drop_index(op.f('ix_TblLogEmployee_created_by'), table_name='TblLogEmployee')
    op.drop_table('TblLogEmployee')
    op.drop_index(op.f('ix_TblEmployee_id'), table_name='TblEmployee')
    op.drop_index(op.f('ix_TblEmployee_employeeId'), table_name='TblEmployee')
    op.drop_table('TblEmployee')
    # ### end Alembic commands ###
