"""empty message

Revision ID: 339511197fdf
Revises: 0e7be7c2d88f
Create Date: 2025-09-19 10:12:55.287755

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '339511197fdf'
down_revision = '0e7be7c2d88f'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TblLogEmplPosition', sa.Column('positionCode', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_TblLogEmplPosition_positionCode'), 'TblLogEmplPosition', ['positionCode'], unique=False)
    op.create_foreign_key(None, 'TblLogEmplPosition', 'TblEmplPosition', ['positionCode'], ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TblLogEmplPosition', type_='foreignkey')
    op.drop_index(op.f('ix_TblLogEmplPosition_positionCode'), table_name='TblLogEmplPosition')
    op.drop_column('TblLogEmplPosition', 'positionCode')
    # ### end Alembic commands ###
