"""empty message

Revision ID: 4d11e907c446
Revises: 665437ed1d06
Create Date: 2025-08-21 14:32:27.752943

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel  # added


# revision identifiers, used by Alembic.
revision = "4d11e907c446"
down_revision = "665437ed1d06"
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "TblJobOrder", type_="foreignkey")
    op.create_foreign_key(
        "TblJobOrder_bpId_fkey", "TblJobOrder", "TblBusinessPartner", ["bpId"], ["id"]
    )
    # ### end Alembic commands ###
