"""empty message

Revision ID: a19c5ebad3f4
Revises: 4d11e907c446
Create Date: 2025-08-21 14:34:38.330874

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'a19c5ebad3f4'
down_revision = '4d11e907c446'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TblJobOrder', sa.Column('bpName', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index('ix_TblJobOrder_bpId', table_name='TblJobOrder')
    op.create_index(op.f('ix_TblJobOrder_bpName'), 'TblJobOrder', ['bpName'], unique=False)
    op.drop_constraint('TblJobOrder_bpId_fkey', 'TblJobOrder', type_='foreignkey')
    op.create_foreign_key(None, 'TblJobOrder', 'TblBusinessPartner', ['bpName'], ['bpName'])
    op.drop_column('TblJobOrder', 'bpId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TblJobOrder', sa.Column('bpId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'TblJobOrder', type_='foreignkey')
    op.create_foreign_key('TblJobOrder_bpId_fkey', 'TblJobOrder', 'TblBusinessPartner', ['bpId'], ['id'])
    op.drop_index(op.f('ix_TblJobOrder_bpName'), table_name='TblJobOrder')
    op.create_index('ix_TblJobOrder_bpId', 'TblJobOrder', ['bpId'], unique=False)
    op.drop_column('TblJobOrder', 'bpName')
    # ### end Alembic commands ###
