"""empty message

Revision ID: 6b34030e1255
Revises: eb48d8f7c492
Create Date: 2025-09-19 09:46:49.848448

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '6b34030e1255'
down_revision = 'eb48d8f7c492'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TblEmplPosition',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_TblEmplPosition_code'), 'TblEmplPosition', ['code'], unique=True)
    op.create_table('TblLogEmplPosition',
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['TblUser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TblLogEmplPosition_created_by'), 'TblLogEmplPosition', ['created_by'], unique=False)
    op.create_index(op.f('ix_TblLogEmplPosition_id'), 'TblLogEmplPosition', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TblLogEmplPosition_id'), table_name='TblLogEmplPosition')
    op.drop_index(op.f('ix_TblLogEmplPosition_created_by'), table_name='TblLogEmplPosition')
    op.drop_table('TblLogEmplPosition')
    op.drop_index(op.f('ix_TblEmplPosition_code'), table_name='TblEmplPosition')
    op.drop_table('TblEmplPosition')
    # ### end Alembic commands ###
