services:
  db:
    image: postgres:15
    container_name: go_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-appdb}
    ports:
      - "5438:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data



